# Generated by Django 5.0.14 on 2026-05-26 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано товаров')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
            ],
            options={
                'verbose_name': 'Сессия скрапинга',
                'verbose_name_plural': 'Сессии скрапинга',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], db_index=True, max_length=10)),
                ('article', models.CharField(max_length=100, verbose_name='Артикул / ID товара')),
                ('search_query', models.CharField(blank=True, help_text='Для Ozon: по какому запросу искать товар. Для WB можно оставить пустым.', max_length=255, null=True, verbose_name='Поисковый запрос (для Ozon, WB игнорирует)')),
                ('priority', models.PositiveSmallIntegerField(default=10, verbose_name='Приоритет (1=высший)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен для парсинга')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Целевой товар',
                'verbose_name_plural': 'Целевые товары',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], db_index=True, max_length=10)),
                ('vendor_sku', models.CharField(db_index=True, help_text='WB: nm_id, Ozon: sku или product_id', max_length=100, verbose_name='Артикул / ID товара')),
                ('title', models.CharField(max_length=500, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Текущая цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена (до скидки)')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на товар')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL главного изображения')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время скрапинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['marketplace', 'vendor_sku'], name='idx_marketplace_sku'), models.Index(fields=['-scraped_at'], name='idx_scraped_at_desc')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('marketplace', 'vendor_sku'), name='unique_marketplace_sku'),
        ),
        migrations.AddConstraint(
            model_name='searchtarget',
            constraint=models.UniqueConstraint(fields=('marketplace', 'article'), name='uniq_marketplace_article_target'),
        ),
    ]
