# Generated by Django 5.0.14 on 2026-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtarget',
            name='search_category',
            field=models.CharField(blank=True, help_text='Для Ozon: URL категории (напр. /category/suhie-korma-dlya-koshek-12349/) или ID категории. WB игнорирует.', max_length=255, null=True, verbose_name='Категория Ozon (URL или ID)'),
        ),
    ]
