# Generated by Django 5.0.14 on 2026-05-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_searchtarget_search_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtarget',
            name='search_category',
        ),
    ]
